#!/bin/bash
sudo yum update -y
sudo yum install httpd -y
sudo systemctl start httpd && sudo systemctl enable httpd
sudo yum install epel-release -y
sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y     
sudo yum-config-manager --enable remi-php70
sudo yum install php php-gd php-mysql -y
sudo yum install wget -y
sudo wget https://wordpress.org/latest.tar.gz
sudo tar -xf latest.tar.gz
sudo cp -a wordpress/* /var/www/html
sudo cp wp-config-sample.php wp-config.php
sudo chown -R apache:apache /var/www/html
sudo systemctl restart httpd